### ISSUE TITLE
How do I remove persistence from a Windows machine?

### ISSUE THREAD

**Issue by AgeOfMarcus** [Arno0x/DBC2#4]
So the persistence works well, too well. How do I remove it from my PC?

**Comment by Arno0x** [comment]
Good point, I didn't code persistence removal :-)
All you need to do is:
1. Delete the scheduled task called "WindowsUserLogRotate"
2. Delete the batch file "%USERPROFILE%\AppData\Local\WindowsUserLogRotate\logrotate.bat"
